/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unillanoside.vistas;

/**
 *
 * @author scbee
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("IGU EDITOR DE TEXTO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelArchivoInicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelTextArchivoInicial = new javax.swing.JTextPane();
        btnCargarArchivo = new javax.swing.JButton();
        PanelArchivoProcesado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelTextArchivoProcesado = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        PanelCargarComponente = new javax.swing.JPanel();
        btnCargarComponente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelComponentesCargados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaComponentes = new javax.swing.JList<>();
        PanelEjecutarComponente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEjecutarComponente = new javax.swing.JButton();
        PanelSalidaMensajes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1000, 800));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelArchivoInicial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelArchivoInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Archivo inicial");
        PanelArchivoInicial.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 20));

        jScrollPane1.setViewportView(PanelTextArchivoInicial);

        PanelArchivoInicial.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 590, 220));

        btnCargarArchivo.setText("Cargar archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        PanelArchivoInicial.add(btnCargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 30));

        PanelPrincipal.add(PanelArchivoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 610, 280));

        PanelArchivoProcesado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelArchivoProcesado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(PanelTextArchivoProcesado);

        PanelArchivoProcesado.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 230));

        jLabel2.setText("Archivo procesado");
        PanelArchivoProcesado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        PanelPrincipal.add(PanelArchivoProcesado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 610, 260));

        PanelCargarComponente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelCargarComponente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargarComponente.setText("Cargar componente");
        btnCargarComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarComponenteActionPerformed(evt);
            }
        });
        PanelCargarComponente.add(btnCargarComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 30));

        jLabel3.setText("Cargar componente");
        PanelCargarComponente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        PanelPrincipal.add(PanelCargarComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 60));

        PanelComponentesCargados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelComponentesCargados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(ListaComponentes);

        PanelComponentesCargados.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 360));

        PanelPrincipal.add(PanelComponentesCargados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 340, 380));

        PanelEjecutarComponente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelEjecutarComponente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Ejecutar componente");
        PanelEjecutarComponente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnEjecutarComponente.setText("Ejecutar componente");
        btnEjecutarComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarComponenteActionPerformed(evt);
            }
        });
        PanelEjecutarComponente.add(btnEjecutarComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 30));

        PanelPrincipal.add(PanelEjecutarComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 340, 60));

        PanelSalidaMensajes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelSalidaMensajes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setViewportView(jTextPane1);

        PanelSalidaMensajes.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 950, 80));

        jLabel5.setText("Salida de mensajes");
        PanelSalidaMensajes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        PanelPrincipal.add(PanelSalidaMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 970, 110));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnCargarComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarComponenteActionPerformed

    private void btnEjecutarComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarComponenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEjecutarComponenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaComponentes;
    private javax.swing.JPanel PanelArchivoInicial;
    private javax.swing.JPanel PanelArchivoProcesado;
    private javax.swing.JPanel PanelCargarComponente;
    private javax.swing.JPanel PanelComponentesCargados;
    private javax.swing.JPanel PanelEjecutarComponente;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSalidaMensajes;
    private javax.swing.JTextPane PanelTextArchivoInicial;
    private javax.swing.JTextPane PanelTextArchivoProcesado;
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnCargarComponente;
    private javax.swing.JButton btnEjecutarComponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
